### ISSUE TITLE
Separate feature/PR/develop/master analysis in Sonar

### ISSUE THREAD

**Issue by j-barber** [GalateaRaj/fuse-starter-java#138]
Currently there's no differentiation between these build types in Sonar, so a branch build could fail the Quality Gate, then a PR build will fix it, and this history doesn't make this clear.

Separate branch/PR/develop/master analysis.

**Comment by j-barber** [comment]
Investigate this plugin: 
https://docs.sonarqube.org/display/PLUG/Branch+Plugin

And also look into this admin section:
https://sonarcloud.io/project/branches?id=org.galatea%3Afuse-starter-java

**Comment by j-barber** [comment]
Sonar differentiates between 'Long-lived' and 'Short-lived' branches, with different levels of analysis performed for each.

To instruct sonar what branch is being built, set the sonar.branch.name in the command to sonar:
```
       stage('SonarQube analysis') {
            steps {
                withSonarQubeEnv('SonarCloud FUSE') {
                    sh "mvn -Dsonar.branch.name=${env.GIT_BRANCH} clean org.jacoco:jacoco-maven-plugin:prepare-agent compile test-compile test sonar:sonar"
                }
            }
```

Sonar then picks this up and tracks the branch based on the value of sonar.branch.name here:
https://sonarcloud.io/project/branches?id=org.galatea%3Afuse-starter-java
![image](https://user-images.githubusercontent.com/23705265/36617673-6fedc8d0-18b6-11e8-9f0e-fc7db8aa14ff.png)

So, by way of addressing this issue:
1. Set the sonar.branch.name value to env.GIT_BRANCH in the Jenkinsfile
2. Instruct sonarcloud to treat just the 'develop' branch as long-lived by setting the naming pattern to develop
3. Confirm things that shouldn't pass Sonar don't, and the branch/PR build fails (since they'll be 'short-lived' branches according to Sonar and are subject to some sub-set of the quality gates).
4. Also, consider telling sonar what branch we'll eventually merge back into (master for develop, develop for everything else) using sonar.branch.target documented [here](https://docs.sonarqube.org/display/PLUG/Branch+Plugin)

**Comment by j-barber** [comment]
'Short-lived' branch analysis looks like this:
![image](https://user-images.githubusercontent.com/23705265/36617943-51608ec4-18b7-11e8-9184-e08c5dcbba8b.png)

**Comment by j-barber** [comment]
TODO: 

1. do we like the functionality of 'short lived' branches?
1.a we only get new bugs, vulnerabilities, and code smells
1.b we don't get coverage stats...
2. would we rather make PRs long-lived, and stomach the manual deletion of them?
2.a We'd get proper quality gate reporting, including coverage
2.b BUT, the quality gate is at the project level, not just for new code, so not incredibly helpful.

**Comment by j-barber** [comment]
'Short Lived' branch analysis output below. The Sonar Analysis stage in the jenkins build fails due to this. But no test coverage...

![image](https://user-images.githubusercontent.com/23705265/36678649-4fd10bc2-1adf-11e8-8753-1e8661e70895.png)

**Comment by j-barber** [comment]
First, some background.
Sonar defines 'short-lived' and 'long-lived' branches. See [here](https://docs.sonarqube.org/display/PLUG/Branch+Plugin) for details.

Short lived branches pass analysis if and only if:
  new_bugs = 0
  new_vulnerabilities = 0
  new_code_smells = 0
**N.B. code coverage is not a factor!**

Long-lived branches pass analysis based on the quality gate defined.
**N.B. Success/failure is based on anlysis of the codebase as a whole, not only new code!**

**_There doesn't seem to be a way to fail analysis based on coverage of new code in either setup._**

Short-lived branches are deleted automatically by sonar after 30 (configurable) days without analysis run.
Long-lived branches must be manually deleted.

Both a short-lived and long-lived branch have been defined on SonarCloud currently for people to play around with and develop opinions: https://sonarcloud.io/dashboard?id=org.galatea%3Afuse-starter-java

Currently develop and Pull Requests are configured as long lived branches, and feature branches (anything other than develop|PR-, really) are defined as short lived.

Sonar suggests both PRs and feature branches be "short-lived".

**_What setup do we want to adopt?_**

**Comment by GalateaEric** [comment]
When you say Sonar deletes short-lived branches automatically after 30 days, does that mean they're deleted in Git as well, or just in Sonar?

I would be a proponent of more automatic deletion (ie, mark PR branches as short lived as well).  Generally I've found any branch that isn't being actively worked on is just clutter.  I have yet to encounter a single case where work done in a branch months ago is resurrected and value is preserved.  

That being said, i think FUSE as a project may be a special case since people roll on and off and we may end up with no one working on anything for several months.  

So, I think if we're trying to model our ideal behavior then treat the PRs as short-lived.  If we're trying to eke out some marginal value from hours spent on FUSE then leave them as long-lived.  Personally I'm in favor of keeping them short-lived and forcing people to do atomic tasks on FUSE.  In part because the hand off of half-finished work after 6 months rarely goes all that well, and the next person may as well just start over.

**Comment by paulo-reichert** [comment]
My 2¢:
- Configure all new branches and PRs as short-lived branches and live with the limitations of SQ not checking code coverage for them.
- Review tests during code review to gauge whether coverage is adequate. 

The caveat here is that a short-lived branch that passed the SQ checks may still fail the quality gate when merged back into develop. That sucks and we may have to deal with it manually.

**Comment by paulo-reichert** [comment]
@GalateaEric this is only for SonarQube. It will not delete the branch from GIT.

Otherwise, I agree with your comments that a branch that has been merged back in develop has no value and should be deleted. I can live with branches that have not been merged hanging around but even then within reason. If it has been untouched for over 1 year while there have been tens of pull requests merged back in develop in that time I'd consider its usefulness highly suspicious.

**Comment by j-barber** [comment]
I'm going to treat both feature and PR builds as 'short-lived' for now, then. 

For future reference, if we want to treat PR builds as long-lived, update the definition here:
https://sonarcloud.io/project/branches?id=org.galatea%3Afuse-starter-java

To:
Long living branches pattern: (develop|PR-.*)
