### ISSUE TITLE
Decide/Configure coding standards

### ISSUE THREAD

**Issue by j-barber** [GalateaRaj/fuse-starter-java#176]
Issue Description
--
Issue #175 covered updating Sonar to allow us to configure Quality Profiles and Quality Gates.
This issue covers deciding what coding standards to enforce, and actually enforcing them.

All Java rules Sonar knows about are here:
https://sonarcloud.io/organizations/default/rules?languages=java

All Java rules currently in the Sonar Way are here:
https://sonarcloud.io/organizations/default/rules?activation=true&languages=java&qprofile=java-sonar-way-45126

All Java rules currently NOT in the Sonar Way are here:
https://sonarcloud.io/organizations/default/rules?activation=false&languages=java&qprofile=java-sonar-way-45126

***Which do we want that we don't have, which do we have that we don't want? Update the table in the comment below***

***And which rules don't exist on Sonar, so we need to look for other means (e.g. Checkstyle) of enforcing them?***

Design
--
Create a 'Galatea Way' quality profile (based off the Sonar Way profile) and update it to include the rules we want.

Run checkstyle as part of the maven build to ensure that code style standards are met, and fail the build if there are any checkstyle failures. Checkstyle will be based on the Google Java style guide, with the additional rule that all method parameters should be final.

Add auto-formatting configuration to Eclipse and IntelliJ that can automatically format code to comply with the checkstyle rules.

Documentation Changes
--
Updated "Getting Started" section of README with info on how to set up formatting in Eclipse and IntelliJ.

Updated "[Galatea Coding Standards]"(https://docs.google.com/document/d/1EqvSfrKaQa6zBF8QRjWMZeOifMZsl-jwCxCmhC2Q8S8/edit#heading=h.f7mkz5md6w3g) section of Fuse documentation with info about checkstyle and Sonar.

Test Evidence
--
A build with code that does not comply with checkstyle rules fails: https://jenkins.fuse.galatea-associates.com/job/jenkins-pipeline/job/feature%252Fissue-176-Configure-coding-standards/2/consoleText

Browse files at commit https://github.com/GalateaRaj/fuse-starter-java/commit/765c79d1f6f0c802140d4dd96cd5604720e17730 to view the state of code after IntelliJ auto-formatting rules were applied, or at commit https://github.com/GalateaRaj/fuse-starter-java/commit/397fcdae12fe53875b0c2d2db23902bb139d8131 to view the state of code after all checkstyle failures have been resolved.

Validation in Develop
-- 
[Proof issue is resolved in Develop. Should be complete before Issue is closed]

**Comment by j-barber** [comment]
Proposals (Edit this post):

| Rule to add | For | Against |
| --- | --- | --- |
| [Keep exception cause](https://sonarcloud.io/organizations/default/rules?activation=false&languages=java&open=squid%3AS1166&qprofile=java-sonar-way-45126) | James, Paulo, Eric, Danny, Sam |  |
| [Require Javadoc on public APIs](https://sonarcloud.io/organizations/galatea/rules?languages=java&open=squid%3AUndocumentedApi&q=javadoc) | Raj, James, Firsh, Heather, Tighe| Paulo, Eric, Danny|
| [Curly brace on line end](https://sonarcloud.io/organizations/galatea/rules?activation=false&languages=java&open=squid%3ALeftCurlyBraceEndLineCheck&q=naming&qprofile=AWILJszGvD4nwDDaI2dx) | James, Paulo, Eric, Sam |  | 
|["Exception" should not be caught when not required by called methods](https://sonarcloud.io/organizations/default/rules?activation=false&languages=java&open=squid%3AS2221&qprofile=java-sonar-way-45126)|Paulo, James, Eric, Sam| |
|["final" classes should not have "protected" members](https://sonarcloud.io/organizations/default/rules?activation=false&languages=java&open=squid%3AS2156&qprofile=java-sonar-way-45126)|Paulo| |
|["java.time" classes should be used for dates and times](https://sonarcloud.io/organizations/default/rules?activation=false&languages=java&open=squid%3AS2143&qprofile=java-sonar-way-45126)|Paulo, Eric| |
|["main" should not "throw" anything](https://sonarcloud.io/organizations/default/rules?activation=false&languages=java&open=squid%3AS2096&qprofile=java-sonar-way-45126)|Paulo, Eric| |
|["NullPointerException" should not be caught](https://sonarcloud.io/organizations/default/rules?activation=false&languages=java&open=squid%3AS1696&qprofile=java-sonar-way-45126)|Paulo| |
|["Lines should have sufficient coverage"](https://sonarcloud.io/organizations/galatea/rules?activation=false&languages=java&open=common-java%3AInsufficientLineCoverage&q=coverage&qprofile=AWILJszGvD4nwDDaI2dx) | James | |
|["Branches should have sufficient coverage"](https://sonarcloud.io/organizations/galatea/rules?activation=false&languages=java&open=common-java%3AInsufficientBranchCoverage&qprofile=AWILJszGvD4nwDDaI2dx) | James | |

| Rule to remove | For | Against |
| --- | --- | --- |

**Comment by GalateaEric** [comment]
I think i'm against requiring javadocs, only because I feel like requiring it leads to these very mechanical javadocs that people slap on there to get it to compile.  Legitimately I think a lot of methods don't actually deserve/need/require a javadoc.  However, some do, but it's too difficult to come up with a blanket rule of when to provide one and when not to provide one that I'd rather err on the side of not requiring them to avoid the garbage javadocs which I think leads to overall weakening of javadoc usage.

**Comment by GalateaRaj** [comment]
I'd like Sonar to ensure we are adhering to the Google style guide (including javadocs).  Has anyone done a rec between the google guide and the sonar way to see if there are gaps that need to be covered by another tool.

In addition to the Google guide, I'd like to require final method parameters and a specific import order.

**Comment by j-barber** [comment]
I didn't accurately represent the rule I was supporting when I described it as "Require Javadoc". The rule is more accurately described as "Public types, methods and fields (API) should be documented with Javadoc". 

@GalateaEric's point that "a lot of methods don't actually need ... javadoc" is a fair one, but can we agree that public methods do? Is there less pushback against this rule?

**Comment by j-barber** [comment]
The Google style guide is described here: https://google.github.io/styleguide/javaguide.html

We can ensure compliance with this guide by re-enabling a checkstyle check. Sonar and the Google style guide do not check all of the same things, so the only way to ensure compliance w/ the Google style guide is with Checkstyle.

However, even the google style guide doesn't enforce javadoc on classes (despite saying they do, in section 7):
![image](https://user-images.githubusercontent.com/23705265/37302149-17c308ac-2601-11e8-8869-64a04c44fb83.png)

https://github.com/checkstyle/checkstyle/blob/60f41e3c16e6c94b0bf8c2e5e4b4accf4ad394ab/src/main/resources/google_checks.xml

**Comment by paulo-reichert** [comment]
When we enforced javadocs in Java or similar in C# in the past we ended up with people brainlessly adding comments. Worse yet, in Visual Studio there is a tool to generate skeleton docs for C# code that people would just use to not fail code style checks but not fill with any useful info.

An example of that is `public class SettlementMission`: what javadoc would add value in that class declaration? In the past, I've seen people (myself included) adding comments such as 'represents a settlement instruction' which doesn't really add any value.

I fully agree with Eric that in some cases javadocs are certainly needed in some code, but given that tools can either enforce it for all or for none, I'd vote to ditch the tool and use developers and reviewers judgment on that.

**Comment by GalateaEric** [comment]
It's a tricky one...  A good javadoc in the right place is worth it's
weight in gold, but I believe a useless javadoc has negative value in that
it leads to a macro cognitive devaluation of javadocs in the minds of
developers working in the code base.

So, I don't like a blanket rule to require javadocs because I think in a
number of cases no javadoc is better than a skeleton/perfunctory javadoc.
But, I don't know how to reflect that in a sonar rule...

**Comment by paulo-reichert** [comment]
After a group discussion, we are moving forward with enforcing all rules listed in the table above, incl. requiring javadocs for all public API.

**Comment by j-barber** [comment]
Did I miss a group discussion?

**Comment by GalateaRaj** [comment]
I'm going to put the decision needed label back on this, since I've lost the plot a bit between this issue and issue #9 .  Here are my ramblings:

1. The build process needs to enforce any standards around code quality and style.  If the build process can't enforce it, we should assume that it won't be done.
2. I concluded that we needed the build process to run both checkstyle AND sonar since sonar doesn't check things like "final modifier on methods".  Does SteerCo agree with that?
3.  Anything we can configure inside the IDE (e.g. code formatting, save actions) helps the developer comply with the standards enforced by the build process.  What does the SteerCo think our options are for Eclipse and Intellij?

**Comment by j-barber** [comment]
1. Agreed.
2. Agreed. Sonar stopped covering all of checkstyle's checks at some point.
We should be sure to validate the checks in whatever checkstyle.xml we go
with, as the google and sun checkstyle.xmls were each missing some useful
checks.
3. Eclipse allows exporting of code cleanup actions, code/comment
templates, formatting templates, import order, and checkstyle config
(though unfortunately not the configuration of save actions).
https://github.com/GalateaRaj/fuse-settings/tree/master/eclipse has these
for eclipse (though the checkstyle.xml should be suspect, per my point #2).
Does IntelliJ have the same options, and can we get them to match what's
configured for Eclipse?

**Comment by GalateaRaj** [comment]
We decided:
1.  @mbarber-gala to configure checkstyle per @hstandring direction (largely based on Google style guide and above discussion re javadoc and the table)
2.  Checkstyle rules will be used via IDE plugin and during maven/gradle build
3.  We all agreed that we need Sonar in additional to checkstyle.  We will utilize the SonarWay.
4.  We should also do #9 in conjunction with this change: @mbarber-gala to create IDE save actions, code templates, etc to be consistent with checkstsyle rules

**Comment by GalateaFarhaad** [comment]
There is an existing Galatea Way profile that is being used for FUSE scans, but it is missing a bunch of rules from the Sonar Way. I did a bulk-import of rules from the Sonar Way to the Galatea Way and then set the Sonar Way as the parent of the Galatea Way, so any changes to the Sonar Way in the future should be automatically reflected in the Galatea Way.

I also added all of the rules in the table above to the Galatea Way. [See diff](https://sonarcloud.io/organizations/galatea/quality_profiles/compare?language=java&name=Galatea+Way&withKey=AWIK3vog-T_TB3XqpAKF). Note that, since they are rules, the line and branch coverage rules apply on a per-file basis. Config and domain classes will be added to a exclusion list (the `sonar.coverage.exclusions` section in the maven pom) so that low coverage on those classes won't trigger failures.

**Comment by j-barber** [comment]
Changes look good. A few more documentation updates and we'll be good to go. I added a few comments directly to the gDoc - once those are resolved we can merge/close this issue.

**Comment by j-barber** [comment]
gDoc updates look good.

**Comment by GalateaFarhaad** [comment]
Removed the line coverage and branch coverage rules, and instead added "Line coverage on new code" and "Condition coverage on new code" quality gates. The rules applied on a per-file basis and did not seem to properly trigger failures on feature/PR builds, possibly because those short-lived-branches only scan modified lines of code, but then when the full project was scanned in the develop build those rules would trigger failures.

**Comment by mikegajda** [comment]
Adding st:already-done label as work seems complete. Waiting on Steering Committee final sign off to close issue
