### ISSUE TITLE
Fix tracer filter to log exceptions correctly

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#88]
Right now MDC is cleared before the servlet handler gets the exception

**Comment by Gala-Sortino** [comment]
Hey @GalateaRaj. Was wondering if you could provide some clarification on this issue, as to how the tracer filter should be acting in this situation.

**Comment by GalateaRaj** [comment]
I'd expect the tracer to log the exception with all of the appropriate request context.

**Comment by Gala-Sortino** [comment]
With the current code, if a generic exception occurs that is not caught by the RestExceptionHandler, then-the tracer log is the following:

`2018.09.20 14:24:35.912 [qtp32836908-27] INFO  o.g.s.u.FuseTraceRepository - 1341475304 - Adding trace info: {Tracer={internal-request-id=1341475304, trace-end-UTC=2018-09-20T13:24:35.912Z, trace-timing-ms=131655, trace-start-UTC=2018-09-20T13:22:24.257Z}, FuseWebRequestTraceFilter={request-error=Handler dispatch failed; nested exception is java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Exception
, spring-trace={method=GET, path=/hal, headers={request={Cookie=__test=1, Cache-Control=max-age=0, Accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8, Upgrade-Insecure-Requests=1, Connection=keep-alive, User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36, Host=127.0.0.1:8080, Accept-Encoding=gzip, deflate, br, Accept-Language=en-GB,en-US;q=0.9,en;q=0.8}, response={X-Application-Context=application:dev, Date=Thu, 20 Sep 2018 13:22:24 GMT, status=500}}, contextPath=, parameters={requestId=[12345], text=[abc]}, query=text=abc&requestId=12345, remoteAddress=127.0.0.1}, request-success=false, response-payload=, request-payload=}}
`

This would seem to contain the error message and the context that caused the request, is this what is expected for this issue?

If this is what is to be expected, then it would indicate a similar issue to #40 since the exception handler is handling exceptions gracefully resulting in the tracer try catch to always succeed and never attempt to add the errors. Thus meaning a new decision is to be made on how to correctly deal with caught exceptions and log them appropriately.

**Comment by GalaHarley** [comment]
For clarification, is this the issue to be addressed? Where MDC elements like request ID disappear after the exception log?

---
2019.08.08 14:44:16.544 [qtp322612414-21] INFO  o.g.s.e.IexRestController - 1425400604 - ↓getLastTradedPrice({})
2019.08.08 14:44:17.798 [qtp322612414-21] ERROR o.g.s.e.IexRestController - 1425400604 - ⇑getLastTradedPrice({}) ⇒ feign.FeignException: status 400 reading IexClient#getLastTradedPriceForSymbols(String[]); content:
{"error":"child \"symbols\" fails because [\"symbols\" is not allowed to be empty]"}
feign.FeignException: status 400 reading IexClient#getLastTradedPriceForSymbols(String[]); content:
{"error":"child \"symbols\" fails because [\"symbols\" is not allowed to be empty]"}
	at feign.FeignException.errorStatus(FeignException.java:62) ~[feign-core-9.5.1.jar:?]
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:91) ~[feign-core-9.5.1.jar:?]
	...
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
2019.08.08 14:44:17.824 [qtp322612414-21] INFO  o.g.s.u.r.FuseWebRequestTraceFilter - 1425400604 - Attempting to add audit headers
2019.08.08 14:44:17.829 [qtp322612414-21] INFO  o.g.s.u.FuseTraceRepository - 1425400604 - Adding trace info: {Tracer={internal-request-id=1425400604, trace-end-UTC=2019-08-08T18:44:17.828Z, trace-timing-ms=1344, trace-start-UTC=2019-08-08T18:44:16.485Z}, FuseWebRequestTraceFilter={request-error=Request processing failed; nested exception is feign.FeignException: status 400 reading IexClient#getLastTradedPriceForSymbols(String[]); content:
{"error":"child \"symbols\" fails because [\"symbols\" is not allowed to be empty]"}, spring-trace={method=GET, path=/iex/lastTradedPrice, headers={request={Accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3, Upgrade-Insecure-Requests=1, Connection=keep-alive, User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36, Host=localhost:8080, Accept-Encoding=gzip, deflate, br, Accept-Language=en-US,en;q=0.9}, response={X-Application-Context=application:dev:8080, Date=Thu, 08 Aug 2019 18:44:16 GMT, status=500}}, contextPath=, parameters={symbols=[]}, query=symbols, remoteAddress=0:0:0:0:0:0:0:1}, request-success=false, response-payload=, request-payload=}}
2019.08.08 14:44:17.833 [qtp322612414-21] WARN  **o.e.j.s.HttpChannel - /iex/lastTradedPrice**
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is feign.FeignException: status 400 reading IexClient#getLastTradedPriceForSymbols(String[]); content:
{"error":"child \"symbols\" fails because [\"symbols\" is not allowed to be empty]"}

**Comment by GalateaEric** [comment]
Let's pause any work on this issue for the moment as our custom trace implementation may be going away with the spring boot 2 migration -- #288

**Comment by GalateaRaj** [comment]
Since #288 is done, RIP tracer.
