### ISSUE TITLE
Show how to log exceptions as one line in log4j2

### ISSUE THREAD

**Issue by GalateaRaj** [GalateaRaj/fuse-starter-java#91]
Design
--

Add _'%xThrowable{separator(|)}'_ to the logging Pattern in all log4j config files (app, stdout and debug).

This replaces new lines on logged exceptions with the pipe (|) symbol.

**Comment by paulo-reichert** [comment]
Can we have a bit more info on the goal here? Not sure why we'd want to log exceptions in one line.

**Comment by hstandring** [comment]
Our project currently uses the ELK stack for gathering logs and searching through them.  Exceptions that span multiple lines are difficult to find because they span across multiple documents (where only the first line of the stack trace has the trace id attached) and are not guaranteed to be written to elastic search in the same order as they were output.  Believe people have faced a similar issue with splunk but I haven't used that as much.  If the whole stack trace was on one line, it would make it easier to find the full details.

**Comment by j-barber** [comment]
Can this issue be updated to clarify what files

**Comment by gala-lightfoot** [comment]
Do we want this applied to all logs, or just to a subset (such as to the error log file), to act as an example?

**Comment by GalateaRaj** [comment]
Should this still have decision needed?  I thought @hstandring provided input.

**Comment by paulo-reichert** [comment]
Looks all good.
